insert into users (id, first_name, last_name) values (1, "first name-1", "last name-1");
insert into users (id, first_name, last_name) values (2, "first name-2", "last name-2");
insert into users (id, first_name, last_name) values (3, "first name-3", "last name-3");
insert into users (id, first_name, last_name) values (4, "first name-4", "last name-4");

insert into posts (id, title, content, created_date) values (1, "title-01", "content of title-01", datetime());
insert into posts (id, title, content, created_date) values (2, "title-02", "content of title-02", datetime());
insert into posts (id, title, content, created_date) values (3, "title-03", "content of title-03", datetime());
insert into posts (id, title, content, created_date) values (4, "title-04", "content of title-04", datetime());
insert into posts (id, title, content, created_date) values (5, "title-05", "content of title-05", datetime());
insert into posts (id, title, content, created_date) values (6, "title-06", "content of title-06", datetime());
insert into posts (id, title, content, created_date) values (7, "title-07", "content of title-07", datetime());
insert into posts (id, title, content, created_date) values (8, "title-08", "content of title-08", datetime());
insert into posts (id, title, content, created_date) values (9, "title-09", "content of title-09", datetime());
insert into posts (id, title, content, created_date) values (10, "title-10", "content of title-10", datetime());
insert into posts (id, title, content, created_date) values (11, "title-11", "content of title-11", datetime());
insert into posts (id, title, content, created_date) values (12, "title-12", "content of title-12", datetime());
insert into posts (id, title, content, created_date) values (13, "title-13", "content of title-13", datetime());
insert into posts (id, title, content, created_date) values (14, "title-14", "content of title-14", datetime());
insert into posts (id, title, content, created_date) values (15, "title-15", "content of title-15", datetime());
insert into posts (id, title, content, created_date) values (16, "title-01", "content of title-01", datetime());
insert into posts (id, title, content, created_date) values (17, "title-02", "content of title-02", datetime());
insert into posts (id, title, content, created_date) values (18, "title-03", "content of title-03", datetime());
insert into posts (id, title, content, created_date) values (19, "title-04", "content of title-04", datetime());
insert into posts (id, title, content, created_date) values (20, "title-05", "content of title-05", datetime());
insert into posts (id, title, content, created_date) values (21, "title-06", "content of title-06", datetime());
insert into posts (id, title, content, created_date) values (22, "title-07", "content of title-07", datetime());
insert into posts (id, title, content, created_date) values (23, "title-08", "content of title-08", datetime());
insert into posts (id, title, content, created_date) values (24, "title-09", "content of title-09", datetime());
insert into posts (id, title, content, created_date) values (25, "title-10", "content of title-10", datetime());
insert into posts (id, title, content, created_date) values (26, "title-11", "content of title-11", datetime());
insert into posts (id, title, content, created_date) values (27, "title-12", "content of title-12", datetime());
insert into posts (id, title, content, created_date) values (28, "title-13", "content of title-13", datetime());
insert into posts (id, title, content, created_date) values (29, "title-14", "content of title-14", datetime());
insert into posts (id, title, content, created_date) values (20, "title-15", "content of title-15", datetime());