insert into version(id, ver) values (1, 1);

insert into users (id, username, passwd, first_name, last_name) values (1, 'usr01', '286755fad04869ca523320acce0dc6a4', 'first name-1', 'last name-1');
insert into users (id, username, passwd, first_name, last_name) values (2, 'usr02', '286755fad04869ca523320acce0dc6a4',  'first name-2', 'last name-2');
insert into users (id, username, passwd, first_name, last_name) values (3, 'usr03', '286755fad04869ca523320acce0dc6a4',  'first name-3', 'last name-3');
insert into users (id, username, passwd, first_name, last_name) values (4, 'usr04', '286755fad04869ca523320acce0dc6a4',  'first name-4', 'last name-4');

insert into posts (id, title, content, created_date) values (5, 'title-05', 'content of title-05', now());
insert into posts (id, title, content, created_date) values (6, 'title-06', 'content of title-06', now());
insert into posts (id, title, content, created_date) values (7, 'title-07', 'content of title-07', now());
insert into posts (id, title, content, created_date) values (8, 'title-08', 'content of title-08', now());
insert into posts (id, title, content, created_date) values (9, 'title-09', 'content of title-09', now());
insert into posts (id, title, content, created_date) values (10, 'title-10', 'content of title-10', now());
insert into posts (id, title, content, created_date) values (11, 'title-11', 'content of title-11', now());
insert into posts (id, title, content, created_date) values (12, 'title-12', 'content of title-12', now());
insert into posts (id, title, content, created_date) values (13, 'title-13', 'content of title-13', now());
insert into posts (id, title, content, created_date) values (14, 'title-14', 'content of title-14', now());
insert into posts (id, title, content, created_date) values (15, 'title-15', 'content of title-15', now());
insert into posts (id, title, content, created_date) values (16, 'title-01', 'content of title-01', now());
insert into posts (id, title, content, created_date) values (17, 'title-02', 'content of title-02', now());
insert into posts (id, title, content, created_date) values (18, 'title-03', 'content of title-03', now());
insert into posts (id, title, content, created_date) values (19, 'title-04', 'content of title-04', now());
insert into posts (id, title, content, created_date) values (20, 'title-05', 'content of title-05', now());
insert into posts (id, title, content, created_date) values (21, 'title-06', 'content of title-06', now());
insert into posts (id, title, content, created_date) values (22, 'title-07', 'content of title-07', now());
insert into posts (id, title, content, created_date) values (23, 'title-08', 'content of title-08', now());
insert into posts (id, title, content, created_date) values (24, 'title-09', 'content of title-09', now());
insert into posts (id, title, content, created_date) values (25, 'title-10', 'content of title-10', now());
insert into posts (id, title, content, created_date) values (26, 'title-11', 'content of title-11', now());
insert into posts (id, title, content, created_date) values (27, 'title-12', 'content of title-12', now());
insert into posts (id, title, content, created_date) values (28, 'title-13', 'content of title-13', now());
insert into posts (id, title, content, created_date) values (29, 'title-14', 'content of title-14', now());
insert into posts (id, title, content, created_date) values (20, 'title-15', 'content of title-15', now());
